### ISSUE TITLE
Release v0.12.0 not marked as latest

### ISSUE THREAD

**Issue by zeha** [thkukuk/wtmpdb#13]
v0.11.0 is still marked as the "Latest" releaes. Github shows that release on the frontpage on https://github.com/thkukuk/wtmpdb. If 0.12.0 is a normal release, please also mark it as "Latest".

**Comment by thkukuk** [comment]
It's not clear what exactly your problem is, that 0.12.0 is not marked as "latest"? It seems it is a problem for you, else you wouldn't have created this issue.

**Comment by zeha** [comment]
I don't understand your reply. My problem was clearly stated, even in the subject: "Release v0.12.0 not marked as latest"

Given 0.12.0 appeared after 0.11.0, it is unclear why it is not marked as the "latest" release. Is it not good? Somehow broken? Not actually the latest release?

**Comment by zeha** [comment]
<img width="1264" alt="Screenshot 2024-05-30 at 20 52 22" src="https://github.com/thkukuk/wtmpdb/assets/26175/801f7bd4-fd3c-4ab5-a0bb-43ab7c9bc4b6">

Can you answer if 0.12.0 is the latest release then?
