### ISSUE TITLE
problem with 32bit systems

### ISSUE THREAD

**Issue by hbfl** [thkukuk/wtmpdb#15]
Hello

I have build wtmpdb on 32 and 64 bit systems, on 64 bit systems the output from last or wtmpdb looks good, 

date
Mon Jul 15 18:25:23 CEST 2024
/var/lib/wtmpdb/wtmp.db begins Mon Jul 15 16:07:50 2024

but on 32 bit systems it shows date from 

date
Mon Jul 15 18:24:44 CEST 2024
/var/lib/wtmpdb/wtmp.db begins Thu Jan  1 02:11:34 1970

installed is glibc-2.37

what can I do to solve that
Thanks
Holger

**Comment by hbfl** [comment]
additional information

I compiled Tumbleweed wtmpdb-0.12.0+git.20240508-1.1.src.rpm with rpmbuild

on 32 bit systems the call of last shows

last
holbru   pts/1        192.168.2.34     Thu Jan  1 02:11 - 02:11  (00:00)
holbru   pts/0        192.168.2.34     Thu Jan  1 02:11 - still logged in
reboot   system boot  5.15.161-eisfair Thu Jan  1 02:11 - still running
holbru   pts/3        192.168.2.34     Thu Jan  1 02:11 - 02:11  (00:00)

/var/lib/wtmpdb/wtmp.db begins Thu Jan  1 02:11:34 1970

the database wtmp.db has the correct unixtimestamp 

PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE wtmp(ID INTEGER PRIMARY KEY, Type INTEGER, User TEXT NOT NULL, Login INTEGER, Logout INTEGER, TTY TEXT, RemoteHost TEXT, Service TEXT) STRICT;
INSERT INTO wtmp VALUES(1,3,'holbru',1721066955107896,1721066973602466,'pts/3','192.168.2.34',NULL);
INSERT INTO wtmp VALUES(2,1,'reboot',1721119484212886,NULL,'~','5.15.161-eisfair-1-SMP',NULL);
INSERT INTO wtmp VALUES(3,3,'holbru',1721119619948747,NULL,'pts/0','192.168.2.34',NULL);
INSERT INTO wtmp VALUES(4,3,'holbru',1721121133141056,1721134503874459,'pts/1','192.168.2.34',NULL);
COMMIT;

**Comment by thkukuk** [comment]
Thanks, there was a variable overflow (which should not have happened) and the check for it was broken, too. Both fixed.

**Comment by hbfl** [comment]
That looks good ;-)
/var/lib/wtmpdb/wtmp.db begins Mon Jul 15 20:09:15 2024

Thanks
