### ISSUE TITLE
Format warnings on 32-bit architectures

### ISSUE THREAD

**Issue by zwenna** [thkukuk/wtmpdb#8]
On 32-bit architectures, where sizeof(long) == 4, there are format warnings. From a local build log on Debian i386:

[5/18] cc -Iwtmpdb.p -I. -I.. -I../include -fdiagnostics-color=always -Wall -Winvalid-pch -Wextra -Wpedantic -D_GNU_SOURCE=1 -DXTSTRINGDEFINES -D_FILE_OFFSET_BITS=64 -D_TIME_BITS=64 -flto=auto -ffat-lto-objects -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -Wbad-function-cast -Wcast-align -Wcast-qual -Wformat-security -Winline -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wshadow -Wstrict-prototypes -Wundef -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIE -MD -MQ wtmpdb.p/src_wtmpdb.c.o -MF wtmpdb.p/src_wtmpdb.c.o.d -o wtmpdb.p/src_wtmpdb.c.o -c ../src/wtmpdb.c
../src/wtmpdb.c: In function ‘calc_time_length’:
../src/wtmpdb.c:194:32: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘uint64_t’ {aka ‘long long unsigned int’} [-Wformat=]
  194 |     snprintf (dst, dstlen, "(%ld+%02ld:%02ld)", days, hours, mins);
      |                              ~~^                ~~~~
      |                                |                |
      |                                long int         uint64_t {aka long long unsigned int}
      |                              %lld
../src/wtmpdb.c:194:38: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 5 has type ‘uint64_t’ {aka ‘long long unsigned int’} [-Wformat=]
  194 |     snprintf (dst, dstlen, "(%ld+%02ld:%02ld)", days, hours, mins);
      |                                  ~~~~^                ~~~~~
      |                                      |                |
      |                                      long int         uint64_t {aka long long unsigned int}
      |                                  %02lld
../src/wtmpdb.c:194:44: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 6 has type ‘uint64_t’ {aka ‘long long unsigned int’} [-Wformat=]
  194 |     snprintf (dst, dstlen, "(%ld+%02ld:%02ld)", days, hours, mins);
      |                                        ~~~~^                 ~~~~
      |                                            |                 |
      |                                            long int          uint64_t {aka long long unsigned int}
      |                                        %02lld
../src/wtmpdb.c:196:35: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘uint64_t’ {aka ‘long long unsigned int’} [-Wformat=]
  196 |     snprintf (dst, dstlen, " (%02ld:%02ld)", hours, mins);
      |                               ~~~~^          ~~~~~
      |                                   |          |
      |                                   long int   uint64_t {aka long long unsigned int}
      |                               %02lld
../src/wtmpdb.c:196:41: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 5 has type ‘uint64_t’ {aka ‘long long unsigned int’} [-Wformat=]
  196 |     snprintf (dst, dstlen, " (%02ld:%02ld)", hours, mins);
      |                                     ~~~~^           ~~~~
      |                                         |           |
      |                                         long int    uint64_t {aka long long unsigned int}
      |                                     %02lld
../src/wtmpdb.c:198:38: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘uint64_t’ {aka ‘long long unsigned int’} [-Wformat=]
  198 |     snprintf (dst, dstlen, " (00:%02ld)", mins);
      |                                  ~~~~^    ~~~~
      |                                      |    |
      |                                      |    uint64_t {aka long long unsigned int}
      |                                      long int
      |                                  %02lld

**Comment by thkukuk** [comment]
Thanks
